version: "3.10"

services:
  app:
    env_file:
      - .env
    volumes:
      - .:/app
      - /home/conan/.cache:/root/.cache
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - HF_TOKEN=$HF_TOKEN
        - OPENAI_API_KEY=$OPENAI_API_KEY
    # devices:
    #   - /dev/neuron0:/dev/neuron0
    ports:
      - target: 8504       ## 컨테이너 내부 포트
        published: 8508    ## 호스트OS에서 공개할 포트
        protocol: tcp      ## 포트 프로토콜
    environment:
      - FLASK_ENV=development
      - MAX_JOBS=4
      - HF_TOKEN=$HF_TOKEN
      - NEO4J_URL=$NEO4J_URL
      - NEO4J_USER=$NEO4J_USER
      - NEO4J_PASSWORD=$NEO4J_PASSWORD
    runtime: nvidia
    networks:
      - qdrant_server
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 16gb
        reservations:
          cpus: '2'
          memory: 16gb
          devices:
          - driver: nvidia
            device_ids: ['0']
            capabilities: [gpu]
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    command: 
      - serve
      - run
      - app.main:build_app
networks:
  qdrant_server:
    external: true
    driver: bridge